
// This file has been generated by the GUI designer. Do not modify.
namespace Stetic
{
    internal class Gui
    {
        private static bool initialized;

        internal static void Initialize(Gtk.Widget iconRenderer)
        {
            if ((initialized == false))
            {
                initialized = true;
            }
        }
    }

    internal class ActionGroups
    {
        public static Gtk.ActionGroup GetActionGroup(System.Type type)
        {
            return GetActionGroup(type.FullName);
        }

        public static Gtk.ActionGroup GetActionGroup(string name)
        {
            return null;
        }
    }
}
