// <auto-generated/>
// This file has been generated by the GUI designer. Do not modify.
namespace GeneticSharp.Runner.GtkApp
{
    public partial class PropertyEditor
    {
        private Gtk.Button buttonCancel;
        private Gtk.Button buttonOk;

        protected virtual void Build()
        {
            Stetic.Gui.Initialize(this);
            // Widget GeneticSharp.Runner.GtkApp.PropertyEditor
            CanDefault = true;
            Name = "GeneticSharp.Runner.GtkApp.PropertyEditor";
            Title = Mono.Unix.Catalog.GetString("PropertiyEditor");
            WindowPosition = ((Gtk.WindowPosition)(2));
            Modal = true;
            DefaultWidth = 100;
            DefaultHeight = 50;
            // Internal child GeneticSharp.Runner.GtkApp.PropertyEditor.VBox
            Gtk.VBox w1 = VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Internal child GeneticSharp.Runner.GtkApp.PropertyEditor.ActionArea
            Gtk.HButtonBox w2 = ActionArea;
            w2.Name = "dialog1_ActionArea";
            w2.Spacing = 10;
            w2.BorderWidth = ((uint)(5));
            w2.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            buttonCancel = new Gtk.Button
            {
                Name = "buttonCancel", UseStock = true, UseUnderline = true, Label = "gtk-cancel"
            };
            AddActionWidget(buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w3 = ((Gtk.ButtonBox.ButtonBoxChild)(w2[buttonCancel]));
            w3.Expand = false;
            w3.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            buttonOk = new Gtk.Button
            {
                CanDefault = true,
                CanFocus = true,
                Name = "buttonOk",
                UseStock = true,
                UseUnderline = true,
                Label = "gtk-ok"
            };
            AddActionWidget(buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w4 = ((Gtk.ButtonBox.ButtonBoxChild)(w2[buttonOk]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            if ((Child != null))
            {
                Child.ShowAll();
            }
            buttonOk.HasDefault = true;
            HasDefault = true;
            Show();
        }
    }
}
