
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
    private Gtk.HBox hbxMain;

    private Gtk.DrawingArea drawingArea;

    private Gtk.VBox vbxConfig;

    private Gtk.VBox vbxSample;

    private Gtk.Label label4;

    private Gtk.ComboBox cmbSample;

    private Gtk.VPaned problemConfigWidgetContainer;

    private Gtk.VBox vbxGA;

    private Gtk.VButtonBox vbbSample;

    private Gtk.HSeparator hseparator1;

    private Gtk.Label label1;

    private Gtk.HBox hbox2;

    private Gtk.Label label2;

    private Gtk.SpinButton sbtPopulationMinSize;

    private Gtk.HBox hbox3;

    private Gtk.Label label3;

    private Gtk.SpinButton sbtPopulationMaxSize;

    private Gtk.HBox hbox11;

    private Gtk.ComboBox cmbGenerationStrategy;

    private Gtk.Button btnEditGenerationStrategy;

    private Gtk.HSeparator hseparator2;

    private Gtk.Label label5;

    private Gtk.HBox hbox5;

    private Gtk.ComboBox cmbSelection;

    private Gtk.Button btnEditSelection;

    private Gtk.HSeparator hseparator4;

    private Gtk.Label label7;

    private Gtk.HBox hbox9;

    private Gtk.Label label10;

    private Gtk.HScale hslCrossoverProbability;

    private Gtk.HBox hbox6;

    private Gtk.ComboBox cmbCrossover;

    private Gtk.Button btnEditCrossover;

    private Gtk.HSeparator hseparator5;

    private Gtk.Label label8;

    private Gtk.HBox hbox8;

    private Gtk.Label label9;

    private Gtk.HScale hslMutationProbability;

    private Gtk.HBox hbox7;

    private Gtk.ComboBox cmbMutation;

    private Gtk.Button btnEditMutation;

    private Gtk.HSeparator hseparator3;

    private Gtk.Label label12;

    private Gtk.HBox hbox12;

    private Gtk.ComboBox cmbReinsertion;

    private Gtk.Button btnEditReinsertion;

    private Gtk.Label label11;

    private Gtk.HBox hbox10;

    private Gtk.ComboBox cmbTermination;

    private Gtk.Button btnEditTermination;

    private Gtk.HSeparator hseparator6;

    private Gtk.Button btnStart;

    private Gtk.Button btnNew;

    private Gtk.Button btnStop;

    private Gtk.Button btnResume;

    protected virtual void Build()
    {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        Name = "MainWindow";
        Title = Mono.Unix.Catalog.GetString("GeneticSharp :: Runner");
        Icon = new Gdk.Pixbuf(System.IO.Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, "./Icon.png"));
        WindowPosition = ((Gtk.WindowPosition)(1));
        Modal = true;
        DefaultWidth = 800;
        DefaultHeight = 600;
        // Container child MainWindow.Gtk.Container+ContainerChild
        hbxMain = new Gtk.HBox {Name = "hbxMain", Spacing = 10, BorderWidth = ((uint) (10))};
        // Container child hbxMain.Gtk.Box+BoxChild
        drawingArea = new Gtk.DrawingArea {Name = "drawingArea"};
        hbxMain.Add(drawingArea);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(hbxMain[drawingArea]));
        w1.Position = 0;
        w1.Padding = ((uint)(1));
        // Container child hbxMain.Gtk.Box+BoxChild
        vbxConfig = new Gtk.VBox {Name = "vbxConfig", Spacing = 6};
        // Container child vbxConfig.Gtk.Box+BoxChild
        vbxSample = new Gtk.VBox {Name = "vbxSample", Spacing = 6};
        // Container child vbxSample.Gtk.Box+BoxChild
        label4 = new Gtk.Label
        {
            Name = "label4", LabelProp = Mono.Unix.Catalog.GetString("Problem")
        };
        vbxSample.Add(label4);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(vbxSample[label4]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbxSample.Gtk.Box+BoxChild
        cmbSample = Gtk.ComboBox.NewText();
        cmbSample.Name = "cmbSample";
        vbxSample.Add(cmbSample);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(vbxSample[cmbSample]));
        w3.Position = 1;
        w3.Expand = false;
        w3.Fill = false;
        // Container child vbxSample.Gtk.Box+BoxChild
        problemConfigWidgetContainer = new Gtk.VPaned
        {
            CanFocus = true, Name = "problemConfigWidgetContainer", Position = 10
        };
        vbxSample.Add(problemConfigWidgetContainer);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(vbxSample[problemConfigWidgetContainer]));
        w4.Position = 2;
        vbxConfig.Add(vbxSample);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(vbxConfig[vbxSample]));
        w5.Position = 0;
        // Container child vbxConfig.Gtk.Box+BoxChild
        vbxGA = new Gtk.VBox
        {
            WidthRequest = 250,
            Name = "vbxGA",
            Spacing = 6
        };
        // Container child vbxGA.Gtk.Box+BoxChild
        vbbSample = new Gtk.VButtonBox {Name = "vbbSample"};
        vbxGA.Add(vbbSample);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(vbxGA[vbbSample]));
        w6.Position = 0;
        // Container child vbxGA.Gtk.Box+BoxChild
        hseparator1 = new Gtk.HSeparator {Name = "hseparator1"};
        vbxGA.Add(hseparator1);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(vbxGA[hseparator1]));
        w7.Position = 1;
        w7.Expand = false;
        w7.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        label1 = new Gtk.Label
        {
            Name = "label1", LabelProp = Mono.Unix.Catalog.GetString("Population size")
        };
        vbxGA.Add(label1);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(vbxGA[label1]));
        w8.Position = 2;
        w8.Expand = false;
        w8.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        hbox2 = new Gtk.HBox {Name = "hbox2", Spacing = 6};
        // Container child hbox2.Gtk.Box+BoxChild
        label2 = new Gtk.Label {Name = "label2", LabelProp = Mono.Unix.Catalog.GetString("Min")};
        hbox2.Add(label2);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(hbox2[label2]));
        w9.Position = 0;
        w9.Expand = false;
        w9.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        sbtPopulationMinSize = new Gtk.SpinButton(2, 10000, 1)
        {
            CanFocus = true,
            Name = "sbtPopulationMinSize",
            Adjustment = {PageIncrement = 10},
            ClimbRate = 1,
            Numeric = true,
            Value = 50
        };
        hbox2.Add(sbtPopulationMinSize);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(hbox2[sbtPopulationMinSize]));
        w10.Position = 1;
        w10.Expand = false;
        w10.Fill = false;
        w10.Padding = ((uint)(3));
        // Container child hbox2.Gtk.Box+BoxChild
        hbox3 = new Gtk.HBox {Name = "hbox3", Spacing = 6};
        // Container child hbox3.Gtk.Box+BoxChild
        label3 = new Gtk.Label {Name = "label3", LabelProp = Mono.Unix.Catalog.GetString("Max")};
        hbox3.Add(label3);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(hbox3[label3]));
        w11.Position = 0;
        w11.Expand = false;
        w11.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        sbtPopulationMaxSize = new Gtk.SpinButton(2, 10000, 1)
        {
            CanFocus = true,
            Name = "sbtPopulationMaxSize",
            Adjustment = {PageIncrement = 10},
            ClimbRate = 1,
            Numeric = true,
            Value = 70
        };
        hbox3.Add(sbtPopulationMaxSize);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(hbox3[sbtPopulationMaxSize]));
        w12.Position = 1;
        w12.Expand = false;
        w12.Fill = false;
        hbox2.Add(hbox3);
        Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(hbox2[hbox3]));
        w13.PackType = ((Gtk.PackType)(1));
        w13.Position = 2;
        w13.Expand = false;
        w13.Fill = false;
        vbxGA.Add(hbox2);
        Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(vbxGA[hbox2]));
        w14.Position = 3;
        w14.Expand = false;
        w14.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        hbox11 = new Gtk.HBox {Name = "hbox11", Spacing = 6};
        // Container child hbox11.Gtk.Box+BoxChild
        cmbGenerationStrategy = Gtk.ComboBox.NewText();
        cmbGenerationStrategy.WidthRequest = 200;
        cmbGenerationStrategy.Name = "cmbGenerationStrategy";
        hbox11.Add(cmbGenerationStrategy);
        Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(hbox11[cmbGenerationStrategy]));
        w15.Position = 0;
        w15.Expand = false;
        w15.Fill = false;
        // Container child hbox11.Gtk.Box+BoxChild
        btnEditGenerationStrategy = new Gtk.Button
        {
            CanFocus = true,
            Name = "btnEditGenerationStrategy",
            UseUnderline = true,
            Label = Mono.Unix.Catalog.GetString("Edit")
        };
        hbox11.Add(btnEditGenerationStrategy);
        Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(hbox11[btnEditGenerationStrategy]));
        w16.Position = 1;
        w16.Expand = false;
        w16.Fill = false;
        vbxGA.Add(hbox11);
        Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(vbxGA[hbox11]));
        w17.Position = 4;
        w17.Expand = false;
        w17.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        hseparator2 = new Gtk.HSeparator {Name = "hseparator2"};
        vbxGA.Add(hseparator2);
        Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(vbxGA[hseparator2]));
        w18.Position = 5;
        w18.Expand = false;
        w18.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        label5 = new Gtk.Label
        {
            Name = "label5", LabelProp = Mono.Unix.Catalog.GetString("Selection")
        };
        vbxGA.Add(label5);
        Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(vbxGA[label5]));
        w19.Position = 6;
        w19.Expand = false;
        w19.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        hbox5 = new Gtk.HBox {Name = "hbox5", Spacing = 6};
        // Container child hbox5.Gtk.Box+BoxChild
        cmbSelection = Gtk.ComboBox.NewText();
        cmbSelection.WidthRequest = 200;
        cmbSelection.Name = "cmbSelection";
        hbox5.Add(cmbSelection);
        Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(hbox5[cmbSelection]));
        w20.Position = 0;
        w20.Expand = false;
        w20.Fill = false;
        // Container child hbox5.Gtk.Box+BoxChild
        btnEditSelection = new Gtk.Button
        {
            CanFocus = true,
            Name = "btnEditSelection",
            UseUnderline = true,
            Label = Mono.Unix.Catalog.GetString("Edit")
        };
        hbox5.Add(btnEditSelection);
        Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(hbox5[btnEditSelection]));
        w21.Position = 1;
        w21.Expand = false;
        w21.Fill = false;
        vbxGA.Add(hbox5);
        Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(vbxGA[hbox5]));
        w22.Position = 7;
        w22.Expand = false;
        w22.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        hseparator4 = new Gtk.HSeparator {Name = "hseparator4"};
        vbxGA.Add(hseparator4);
        Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(vbxGA[hseparator4]));
        w23.Position = 8;
        w23.Expand = false;
        w23.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        label7 = new Gtk.Label
        {
            Name = "label7", LabelProp = Mono.Unix.Catalog.GetString("Crossover")
        };
        vbxGA.Add(label7);
        Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(vbxGA[label7]));
        w24.Position = 9;
        w24.Expand = false;
        w24.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        hbox9 = new Gtk.HBox {Name = "hbox9", Spacing = 6};
        // Container child hbox9.Gtk.Box+BoxChild
        label10 = new Gtk.Label
        {
            Name = "label10", LabelProp = Mono.Unix.Catalog.GetString("Probability")
        };
        hbox9.Add(label10);
        Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(hbox9[label10]));
        w25.Position = 0;
        w25.Expand = false;
        w25.Fill = false;
        // Container child hbox9.Gtk.Box+BoxChild
        hslCrossoverProbability = new Gtk.HScale(null)
        {
            CanFocus = true,
            Name = "hslCrossoverProbability",
            Adjustment =
            {
                Upper = 1.1,
                PageIncrement = 0.1,
                PageSize = 0.1,
                StepIncrement = 0.01,
                Value = 0.01
            },
            DrawValue = true,
            Digits = 2,
            ValuePos = ((Gtk.PositionType) (2))
        };
        hbox9.Add(hslCrossoverProbability);
        Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(hbox9[hslCrossoverProbability]));
        w26.Position = 1;
        vbxGA.Add(hbox9);
        Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(vbxGA[hbox9]));
        w27.Position = 10;
        w27.Expand = false;
        w27.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        hbox6 = new Gtk.HBox {Name = "hbox6", Spacing = 6};
        // Container child hbox6.Gtk.Box+BoxChild
        cmbCrossover = Gtk.ComboBox.NewText();
        cmbCrossover.WidthRequest = 200;
        cmbCrossover.Name = "cmbCrossover";
        hbox6.Add(cmbCrossover);
        Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(hbox6[cmbCrossover]));
        w28.Position = 0;
        w28.Expand = false;
        w28.Fill = false;
        // Container child hbox6.Gtk.Box+BoxChild
        btnEditCrossover = new Gtk.Button
        {
            CanFocus = true,
            Name = "btnEditCrossover",
            UseUnderline = true,
            Label = Mono.Unix.Catalog.GetString("Edit")
        };
        hbox6.Add(btnEditCrossover);
        Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(hbox6[btnEditCrossover]));
        w29.Position = 1;
        w29.Expand = false;
        w29.Fill = false;
        vbxGA.Add(hbox6);
        Gtk.Box.BoxChild w30 = ((Gtk.Box.BoxChild)(vbxGA[hbox6]));
        w30.Position = 11;
        w30.Expand = false;
        w30.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        hseparator5 = new Gtk.HSeparator {Name = "hseparator5"};
        vbxGA.Add(hseparator5);
        Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(vbxGA[hseparator5]));
        w31.Position = 12;
        w31.Expand = false;
        w31.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        label8 = new Gtk.Label
        {
            Name = "label8", LabelProp = Mono.Unix.Catalog.GetString("Mutation")
        };
        vbxGA.Add(label8);
        Gtk.Box.BoxChild w32 = ((Gtk.Box.BoxChild)(vbxGA[label8]));
        w32.Position = 13;
        w32.Expand = false;
        w32.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        hbox8 = new Gtk.HBox {Name = "hbox8", Spacing = 6};
        // Container child hbox8.Gtk.Box+BoxChild
        label9 = new Gtk.Label
        {
            Name = "label9", LabelProp = Mono.Unix.Catalog.GetString("Probability")
        };
        hbox8.Add(label9);
        Gtk.Box.BoxChild w33 = ((Gtk.Box.BoxChild)(hbox8[label9]));
        w33.Position = 0;
        w33.Expand = false;
        w33.Fill = false;
        // Container child hbox8.Gtk.Box+BoxChild
        hslMutationProbability = new Gtk.HScale(null)
        {
            CanFocus = true,
            Name = "hslMutationProbability",
            Adjustment = {Upper = 1.1, PageIncrement = 0.1, PageSize = 0.1, StepIncrement = 0.01},
            DrawValue = true,
            Digits = 2,
            ValuePos = ((Gtk.PositionType) (2))
        };
        hbox8.Add(hslMutationProbability);
        Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(hbox8[hslMutationProbability]));
        w34.Position = 1;
        vbxGA.Add(hbox8);
        Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(vbxGA[hbox8]));
        w35.Position = 14;
        w35.Expand = false;
        w35.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        hbox7 = new Gtk.HBox {Name = "hbox7", Spacing = 6};
        // Container child hbox7.Gtk.Box+BoxChild
        cmbMutation = Gtk.ComboBox.NewText();
        cmbMutation.WidthRequest = 200;
        cmbMutation.Name = "cmbMutation";
        hbox7.Add(cmbMutation);
        Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(hbox7[cmbMutation]));
        w36.Position = 0;
        w36.Expand = false;
        w36.Fill = false;
        // Container child hbox7.Gtk.Box+BoxChild
        btnEditMutation = new Gtk.Button
        {
            CanFocus = true,
            Name = "btnEditMutation",
            UseUnderline = true,
            Label = Mono.Unix.Catalog.GetString("Edit")
        };
        hbox7.Add(btnEditMutation);
        Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(hbox7[btnEditMutation]));
        w37.Position = 1;
        w37.Expand = false;
        w37.Fill = false;
        vbxGA.Add(hbox7);
        Gtk.Box.BoxChild w38 = ((Gtk.Box.BoxChild)(vbxGA[hbox7]));
        w38.Position = 15;
        w38.Expand = false;
        w38.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        hseparator3 = new Gtk.HSeparator {Name = "hseparator3"};
        vbxGA.Add(hseparator3);
        Gtk.Box.BoxChild w39 = ((Gtk.Box.BoxChild)(vbxGA[hseparator3]));
        w39.Position = 16;
        w39.Expand = false;
        w39.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        label12 = new Gtk.Label
        {
            Name = "label12", LabelProp = Mono.Unix.Catalog.GetString("Reinsertion")
        };
        vbxGA.Add(label12);
        Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(vbxGA[label12]));
        w40.Position = 17;
        w40.Expand = false;
        w40.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        hbox12 = new Gtk.HBox {Name = "hbox12", Spacing = 6};
        // Container child hbox12.Gtk.Box+BoxChild
        cmbReinsertion = Gtk.ComboBox.NewText();
        cmbReinsertion.WidthRequest = 200;
        cmbReinsertion.Name = "cmbTermination1";
        hbox12.Add(cmbReinsertion);
        Gtk.Box.BoxChild w41 = ((Gtk.Box.BoxChild)(hbox12[cmbReinsertion]));
        w41.Position = 0;
        w41.Expand = false;
        w41.Fill = false;
        // Container child hbox12.Gtk.Box+BoxChild
        btnEditReinsertion = new Gtk.Button
        {
            CanFocus = true,
            Name = "btnEditReinsertion",
            UseUnderline = true,
            Label = Mono.Unix.Catalog.GetString("Edit")
        };
        hbox12.Add(btnEditReinsertion);
        Gtk.Box.BoxChild w42 = ((Gtk.Box.BoxChild)(hbox12[btnEditReinsertion]));
        w42.Position = 1;
        w42.Expand = false;
        w42.Fill = false;
        vbxGA.Add(hbox12);
        Gtk.Box.BoxChild w43 = ((Gtk.Box.BoxChild)(vbxGA[hbox12]));
        w43.Position = 18;
        w43.Expand = false;
        w43.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        label11 = new Gtk.Label
        {
            Name = "label11", LabelProp = Mono.Unix.Catalog.GetString("Termination")
        };
        vbxGA.Add(label11);
        Gtk.Box.BoxChild w44 = ((Gtk.Box.BoxChild)(vbxGA[label11]));
        w44.Position = 19;
        w44.Expand = false;
        w44.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        hbox10 = new Gtk.HBox {Name = "hbox10", Spacing = 6};
        // Container child hbox10.Gtk.Box+BoxChild
        cmbTermination = Gtk.ComboBox.NewText();
        cmbTermination.WidthRequest = 200;
        cmbTermination.Name = "cmbTermination";
        hbox10.Add(cmbTermination);
        Gtk.Box.BoxChild w45 = ((Gtk.Box.BoxChild)(hbox10[cmbTermination]));
        w45.Position = 0;
        w45.Expand = false;
        w45.Fill = false;
        // Container child hbox10.Gtk.Box+BoxChild
        btnEditTermination = new Gtk.Button
        {
            CanFocus = true,
            Name = "btnEditTermination",
            UseUnderline = true,
            Label = Mono.Unix.Catalog.GetString("Edit")
        };
        hbox10.Add(btnEditTermination);
        Gtk.Box.BoxChild w46 = ((Gtk.Box.BoxChild)(hbox10[btnEditTermination]));
        w46.Position = 1;
        w46.Expand = false;
        w46.Fill = false;
        vbxGA.Add(hbox10);
        Gtk.Box.BoxChild w47 = ((Gtk.Box.BoxChild)(vbxGA[hbox10]));
        w47.Position = 20;
        w47.Expand = false;
        w47.Fill = false;
        // Container child vbxGA.Gtk.Box+BoxChild
        hseparator6 = new Gtk.HSeparator {Name = "hseparator6"};
        vbxGA.Add(hseparator6);
        Gtk.Box.BoxChild w48 = ((Gtk.Box.BoxChild)(vbxGA[hseparator6]));
        w48.Position = 21;
        w48.Expand = false;
        w48.Fill = false;
        vbxConfig.Add(vbxGA);
        Gtk.Box.BoxChild w49 = ((Gtk.Box.BoxChild)(vbxConfig[vbxGA]));
        w49.Position = 1;
        // Container child vbxConfig.Gtk.Box+BoxChild
        btnStart = new Gtk.Button
        {
            CanFocus = true,
            Name = "btnStart",
            UseUnderline = true,
            Label = Mono.Unix.Catalog.GetString("_Start")
        };
        vbxConfig.Add(btnStart);
        Gtk.Box.BoxChild w50 = ((Gtk.Box.BoxChild)(vbxConfig[btnStart]));
        w50.Position = 2;
        w50.Expand = false;
        w50.Fill = false;
        // Container child vbxConfig.Gtk.Box+BoxChild
        btnNew = new Gtk.Button
        {
            CanFocus = true,
            Name = "btnNew",
            UseUnderline = true,
            Label = Mono.Unix.Catalog.GetString("_New")
        };
        vbxConfig.Add(btnNew);
        Gtk.Box.BoxChild w51 = ((Gtk.Box.BoxChild)(vbxConfig[btnNew]));
        w51.Position = 3;
        w51.Expand = false;
        w51.Fill = false;
        // Container child vbxConfig.Gtk.Box+BoxChild
        btnStop = new Gtk.Button
        {
            CanFocus = true,
            Name = "btnStop",
            UseUnderline = true,
            Label = Mono.Unix.Catalog.GetString("_Stop")
        };
        vbxConfig.Add(btnStop);
        Gtk.Box.BoxChild w52 = ((Gtk.Box.BoxChild)(vbxConfig[btnStop]));
        w52.Position = 4;
        w52.Expand = false;
        w52.Fill = false;
        // Container child vbxConfig.Gtk.Box+BoxChild
        btnResume = new Gtk.Button
        {
            CanFocus = true,
            Name = "btnResume",
            UseUnderline = true,
            Label = Mono.Unix.Catalog.GetString("_Resume")
        };
        vbxConfig.Add(btnResume);
        Gtk.Box.BoxChild w53 = ((Gtk.Box.BoxChild)(vbxConfig[btnResume]));
        w53.Position = 5;
        w53.Expand = false;
        w53.Fill = false;
        hbxMain.Add(vbxConfig);
        Gtk.Box.BoxChild w54 = ((Gtk.Box.BoxChild)(hbxMain[vbxConfig]));
        w54.Position = 1;
        w54.Expand = false;
        w54.Fill = false;
        Add(hbxMain);
        if ((Child != null))
        {
            Child.ShowAll();
        }
        btnResume.Hide();
        Show();
        DeleteEvent += new Gtk.DeleteEventHandler(OnDeleteEvent);
    }
}
