//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace GeneticSharp.Runner.ConsoleApp.Samples.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class SamplesResource {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SamplesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("GeneticSharp.Runner.ConsoleApp.Samples.Resources.SamplesResource", typeof(SamplesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;type&quot;: &quot;success&quot;,
        ///    &quot;value&quot;: [{
        ///        &quot;id&quot;: 347,
        ///        &quot;joke&quot;: &quot;Some people ask for a Kleenex when they sneeze, Chuck Norris asks for a body bag.&quot;,
        ///        &quot;categories&quot;: []
        ///    }, {
        ///        &quot;id&quot;: 555,
        ///        &quot;joke&quot;: &quot;Chuck Norris doesn&apos;t have pubic hairs because hair doesn&apos;t grow on balls of steal.&quot;,
        ///        &quot;categories&quot;: [&quot;explicit&quot;]
        ///    }, {
        ///        &quot;id&quot;: 252,
        ///        &quot;joke&quot;: &quot;Saddam Hussein was not found hiding in a &amp;quot;hole.&amp;quot; Saddam was roundhouse-kicked in the head by C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GhostwriterQuoteJson {
            get {
                return ResourceManager.GetString("GhostwriterQuoteJson", resourceCulture);
            }
        }
    }
}
